# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://fit2cloud.com
headtitle: FIT2CLOUD
title: FIT2CLOUD - 业界领先的云管理平台（CMP）
email: support@fit2cloud.com
author: fit2cloud
description: "FIT2CLOUD 是业界领先的云管理平台（CMP）提供商，帮助企业管好云资源、控好云成本、用好云服务，更好地使用云和持续交付来加速业务创新，实现数字化转型和“Fit to Cloud”的愿景。"
keywords: "云管理平台，CMP，DevOps平台，DevOps协作平台，云费用管理，云费用管理平台，混合云管理，混合云管理平台，自动化部署，持续集成，持续部署"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - icon-font: weibo
    title: 微博
    url: https://weibo.com/fit2cloud
  - icon-font: mail-reply-all
    title: 邮件
    url: mailto:support@fit2cloud.com
