# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://fit2cloud.com
title: FIT2CLOUD
email: support@fit2cloud.com
author: fit2cloud
description: > # "Official FIT2CLOUD Site"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - icon-font: weibo
    title: 微博
    url: https://weibo.com/fit2cloud
  - icon-font: mail-reply-all
    title: 邮件
    url: mailto:support@fit2cloud.com
